version: "3.8"

services:
  etc_meisai:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/etc_meisai.db
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - LOG_LEVEL=info
      - GRPC_DB_SERVICE_ADDRESS=db_service:50051
    volumes:
      - ./data:/root/data
      - ./logs:/root/logs
      - ./temp:/root/temp
    depends_on:
      - db_service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db_service:
    # db_serviceのイメージ設定（別途作成が必要）
    image: db_service:latest
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=etc_meisai
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=etc_meisai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 開発用のPgAdmin（オプション）
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - dev

volumes:
  postgres_data:

networks:
  default:
    name: etc_meisai_network
