openapi: 3.0.0
info:
  title: Dtako Mapping API
  version: 1.0.0
  description: API for managing ETC-Dtako data mapping

paths:
  /api/etc/mapping/sync-dtako:
    post:
      summary: プロダクションDBからDtakoデータを同期
      operationId: syncDtakoData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - start_date
                - end_date
              properties:
                start_date:
                  type: string
                  format: date
                  description: 同期開始日
                end_date:
                  type: string
                  format: date
                  description: 同期終了日
                vehicle_ids:
                  type: array
                  items:
                    type: string
                  description: 車両IDリスト（省略時は全車両）
      responses:
        '200':
          description: 同期成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncResponse'
        '400':
          description: 不正なリクエスト
        '500':
          description: サーバーエラー

  /api/etc/mapping/auto-match:
    post:
      summary: ETC明細とDtakoデータの自動マッチング実行
      operationId: autoMatchRecords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - start_date
                - end_date
              properties:
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
                confidence_threshold:
                  type: integer
                  minimum: 0
                  maximum: 100
                  default: 50
                  description: マッチング信頼度閾値
      responses:
        '200':
          description: マッチング完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchingResponse'

  /api/etc/mapping/batch:
    post:
      summary: バッチマッピング処理の開始
      operationId: startBatchMapping
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - start_date
                - end_date
              properties:
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
                batch_size:
                  type: integer
                  default: 1000
                  description: バッチサイズ
                parallel_workers:
                  type: integer
                  default: 10
                  maximum: 20
                  description: 並列実行ワーカー数
      responses:
        '202':
          description: バッチ処理開始
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJobResponse'

  /api/etc/mapping/batch/{jobId}:
    get:
      summary: バッチジョブのステータス取得
      operationId: getBatchJobStatus
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: ジョブステータス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJobStatus'

  /api/etc/mapping/dtako/{rowId}:
    get:
      summary: Dtakoレコードの詳細取得
      operationId: getDtakoRecord
      parameters:
        - name: rowId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dtakoレコード詳細
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DtakoRecord'

components:
  schemas:
    SyncResponse:
      type: object
      properties:
        success:
          type: boolean
        synced_count:
          type: integer
          description: 同期されたレコード数
        cached_count:
          type: integer
          description: キャッシュされたレコード数
        message:
          type: string

    MatchingResponse:
      type: object
      properties:
        success:
          type: boolean
        total_etc_records:
          type: integer
        matched_count:
          type: integer
        exact_matches:
          type: integer
          description: 完全一致数
        partial_matches:
          type: integer
          description: 部分一致数
        candidates:
          type: integer
          description: 候補数
        unmatched:
          type: integer
          description: 未マッチ数
        details:
          type: array
          items:
            $ref: '#/components/schemas/MatchingDetail'

    MatchingDetail:
      type: object
      properties:
        etc_meisai_id:
          type: integer
        dtako_row_id:
          type: string
        confidence_level:
          type: integer
        mapping_type:
          type: string
          enum:
            - auto_exact
            - auto_partial
            - auto_candidate
            - manual

    BatchJobResponse:
      type: object
      properties:
        job_id:
          type: integer
        status:
          type: string
          enum:
            - pending
            - running
            - completed
            - failed
            - cancelled
        message:
          type: string

    BatchJobStatus:
      type: object
      properties:
        job_id:
          type: integer
        status:
          type: string
        total_records:
          type: integer
        processed_records:
          type: integer
        matched_records:
          type: integer
        error_count:
          type: integer
        error_details:
          type: string
        progress_percentage:
          type: number
          format: float
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        estimated_completion:
          type: string
          format: date-time

    DtakoRecord:
      type: object
      properties:
        row_id:
          type: string
        vehicle_id:
          type: string
        date:
          type: string
          format: date
        start_time:
          type: string
          format: time
        end_time:
          type: string
          format: time
        distance:
          type: number
          format: float
        driver_id:
          type: string
        route_name:
          type: string
        created_at:
          type: string
          format: date-time