openapi: 3.0.3
info:
  title: ETC明細APIシステム
  description: |
    ETC明細の自動取得、データ管理、およびDtako連携機能を提供するAPIシステム

    ## 主な機能
    - **ETC明細ダウンロード**: 複数アカウントに対応した同期・非同期のETC明細データ取得
    - **ハッシュベースインポート**: 重複検出と変更追跡機能を備えたCSVインポート
    - **マッピング管理**: ETC明細とDtako行の紐付け管理
    - **データ保存・処理**: ローカルデータベースへの保存とバッチ処理

    ## 認証
    このAPIは現在認証なしで動作しますが、本番環境では適切な認証機構の実装を推奨します。

    ## エラーハンドリング
    すべてのエンドポイントで標準的なHTTPステータスコードとJSONエラーレスポンスを使用します。

  version: 0.0.16
  contact:
    name: ETC明細APIサポート
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080
    description: 開発環境
  - url: https://etc-api.example.com
    description: 本番環境

paths:
  # ヘルスチェック
  /health:
    get:
      summary: ヘルスチェック
      description: APIサーバーの稼働状態を確認
      tags:
        - System
      responses:
        '200':
          description: サーバー正常稼働
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-01-13T15:04:05Z"

  # アカウント関連
  /api/etc/accounts:
    get:
      summary: 利用可能なアカウント一覧取得
      description: 環境変数に設定されているアカウント名の一覧を取得（パスワードは表示しない）
      tags:
        - Accounts
      responses:
        '200':
          description: アカウント一覧
          content:
            application/json:
              schema:
                type: object
                properties:
                  configured:
                    type: boolean
                    description: アカウントが設定されているか
                  accounts:
                    type: array
                    items:
                      type: string
                    description: アカウント名の一覧
                  count:
                    type: integer
                    description: アカウント数
                  message:
                    type: string
                    description: 設定状態のメッセージ

  # ダウンロード関連（外部ファイルで詳細定義）
  /api/etc/download:
    $ref: './download-api.yaml#/paths/~1api~1etc~1download'

  /api/etc/download-single:
    $ref: './download-api.yaml#/paths/~1api~1etc~1download-single'

  /api/etc/download-async:
    $ref: './download-api.yaml#/paths/~1api~1etc~1download-async'

  /api/etc/download-status/{job_id}:
    $ref: './download-api.yaml#/paths/~1api~1etc~1download-status~1{job_id}'

  # ハッシュベースインポート（外部ファイルで詳細定義）
  /api/etc/import/hash:
    $ref: './hash-import-api.yaml#/paths/~1api~1etc~1import~1hash'

  /api/etc/diff/{session_id}:
    $ref: './hash-import-api.yaml#/paths/~1api~1etc~1diff~1{session_id}'

  /api/etc/duplicates:
    $ref: './hash-import-api.yaml#/paths/~1api~1etc~1duplicates'

  /api/etc/hash/stats:
    $ref: './hash-import-api.yaml#/paths/~1api~1etc~1hash~1stats'

  /api/etc/hash/clear:
    $ref: './hash-import-api.yaml#/paths/~1api~1etc~1hash~1clear'

  # マッピング管理（外部ファイルで詳細定義）
  /api/etc/mapping:
    $ref: './mapping-api.yaml#/paths/~1api~1etc~1mapping'

  /api/etc/mapping/{id}:
    $ref: './mapping-api.yaml#/paths/~1api~1etc~1mapping~1{id}'

  /api/etc/mapping/by-meisai/{meisai_id}:
    $ref: './mapping-api.yaml#/paths/~1api~1etc~1mapping~1by-meisai~1{meisai_id}'

  /api/etc/mapping/by-dtako/{dtako_row_id}:
    $ref: './mapping-api.yaml#/paths/~1api~1etc~1mapping~1by-dtako~1{dtako_row_id}'

  /api/etc/mapping/list:
    $ref: './mapping-api.yaml#/paths/~1api~1etc~1mapping~1list'

  /api/etc/mapping/unmapped:
    $ref: './mapping-api.yaml#/paths/~1api~1etc~1mapping~1unmapped'

  # CSVパース
  /api/etc/parse-csv:
    post:
      summary: CSVファイルパース
      description: アップロードされたCSVファイルをパース
      tags:
        - Parse
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: パース対象のCSVファイル
      responses:
        '200':
          description: パース成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  # データ処理・保存
  /api/etc/process-download:
    post:
      summary: ETC明細ダウンロードデータ処理
      description: ダウンロードしたETC明細データをdtako_rowsと紐付けて処理
      tags:
        - Processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessDownloadRequest'
      responses:
        '200':
          description: 処理完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessDownloadResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/etc/save-data:
    post:
      summary: ETC明細データをローカルDBに保存
      description: ダウンロードしたETC明細データをローカルのetc_meisaiテーブルに保存
      tags:
        - Save
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveETCDataRequest'
      responses:
        '200':
          description: 保存完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveETCDataResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/etc/save-job/{job_id}:
    post:
      summary: ジョブ結果をローカルDBに保存
      description: 完了したダウンロードジョブの結果をローカルのetc_meisaiテーブルに保存
      tags:
        - Save
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
          description: ジョブID
        - name: link_mode
          in: query
          required: false
          schema:
            type: boolean
            default: false
          description: dtako_rowsとの紐付けを行うか
      responses:
        '200':
          description: 保存完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveETCDataResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

tags:
  - name: System
    description: システム関連のエンドポイント
  - name: Accounts
    description: アカウント管理
  - name: Download
    description: ETC明細ダウンロード機能
  - name: Import
    description: ハッシュベースインポート機能
  - name: Mapping
    description: ETC明細とDtako行の紐付け管理
  - name: Parse
    description: CSVファイル解析
  - name: Processing
    description: データ処理機能
  - name: Save
    description: データ保存機能

components:
  schemas:
    # 基本的なETC明細データ構造
    ETCMeisai:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID
        date_to:
          type: string
          format: date-time
          description: 利用日時（至）
        etc_num:
          type: string
          description: ETCカード番号
        price:
          type: integer
          description: 通行料金
        dtako_row_id:
          type: string
          description: デジタコ運行ID
          nullable: true
        unko_no:
          type: string
          description: 運行NO
        date:
          type: string
          format: date
          description: 日付
        time:
          type: string
          description: 時刻
        ic_entry:
          type: string
          description: IC入口
        ic_exit:
          type: string
          description: IC出口
        vehicle_no:
          type: string
          description: 車両番号
        card_no:
          type: string
          description: ETCカード番号
        amount:
          type: integer
          description: 利用金額
        discount_amount:
          type: integer
          description: 割引金額
        total_amount:
          type: integer
          description: 請求金額
        usage_type:
          type: string
          description: 利用区分
        payment_method:
          type: string
          description: 支払方法
        route_code:
          type: string
          description: 路線コード
        distance:
          type: number
          format: double
          description: 走行距離
        toll_gate:
          type: string
          description: 料金所名
        vehicle_type:
          type: string
          description: 車種
        remarks:
          type: string
          description: 備考
        created_at:
          type: string
          format: date-time
          description: 作成日時
          nullable: true
        updated_at:
          type: string
          format: date-time
          description: 更新日時
          nullable: true

    # 処理リクエスト
    ProcessDownloadRequest:
      type: object
      properties:
        job_id:
          type: string
          description: ジョブID
        csv_path:
          type: string
          description: CSVファイルパス
        link_dtako:
          type: boolean
          description: dtako_rowsとの紐付けを行うか
          default: false

    # 処理レスポンス
    ProcessDownloadResponse:
      type: object
      properties:
        status:
          type: string
          enum: [processing, completed, failed]
          description: 処理ステータス
        processed_count:
          type: integer
          description: 処理済みレコード数
        linked_count:
          type: integer
          description: 紐付け済みレコード数
        error_count:
          type: integer
          description: エラーレコード数
        results:
          type: array
          items:
            $ref: '#/components/schemas/ProcessingResult'

    # 処理結果
    ProcessingResult:
      type: object
      properties:
        etc_meisai_id:
          type: integer
          format: int64
          description: ETC明細ID
        date_to:
          type: string
          format: date-time
          description: 利用日時
        etc_num:
          type: string
          description: ETCカード番号
        price:
          type: integer
          description: 通行料金
        dtako_row_id:
          type: string
          description: デジタコ運行ID
          nullable: true
        vehicle_id:
          type: string
          description: 車両ID
          nullable: true
        status:
          type: string
          enum: [processed, linked, already_linked, error]
          description: 処理ステータス
        error:
          type: string
          description: エラーメッセージ
          nullable: true

    # 保存リクエスト
    SaveETCDataRequest:
      type: object
      properties:
        job_id:
          type: string
          description: ジョブID
        records:
          type: array
          items:
            $ref: '#/components/schemas/ETCMeisai'
          description: 保存対象のETC明細レコード
        link_mode:
          type: boolean
          description: dtako_rowsとの紐付けを行うか
          default: false

    # 保存レスポンス
    SaveETCDataResponse:
      type: object
      properties:
        status:
          type: string
          enum: [processing, completed, partial, failed]
          description: 保存ステータス
        saved_count:
          type: integer
          description: 保存済みレコード数
        linked_count:
          type: integer
          description: 紐付け済みレコード数
        error_count:
          type: integer
          description: エラーレコード数
        results:
          type: array
          items:
            $ref: '#/components/schemas/SaveResult'
        errors:
          type: array
          items:
            type: string
          description: エラーメッセージ一覧

    # 保存結果
    SaveResult:
      type: object
      properties:
        original_index:
          type: integer
          format: int64
          description: 元のインデックス
        saved_id:
          type: integer
          format: int64
          description: 保存済みID
        date_to:
          type: string
          format: date-time
          description: 利用日時
        etc_num:
          type: string
          description: ETCカード番号
        price:
          type: integer
          description: 通行料金
        dtako_row_id:
          type: string
          description: デジタコ運行ID
          nullable: true
        status:
          type: string
          enum: [saved, linked, already_linked, error]
          description: 保存ステータス
        error:
          type: string
          description: エラーメッセージ
          nullable: true

    # エラーレスポンス
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: エラーメッセージ
        details:
          type: string
          description: 詳細情報
          nullable: true
        timestamp:
          type: string
          format: date-time
          description: エラー発生時刻

  responses:
    BadRequest:
      description: 不正なリクエスト
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: "Invalid request parameters"

    NotFound:
      description: リソースが見つからない
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: "Resource not found"

    InternalServerError:
      description: 内部サーバーエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: "Internal server error"

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API認証キー（将来実装予定）

security: []